### ISSUE TITLE
When dash.json can not be retrieved, no message is shown

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerLabs/project-health#225]
I had an error (I don't recall correctly which one, I thought it was a 500) on `dash.json`, which broke the webpage. In this case, it kept saying "Loading" with no change. Looking at the console showed the network error, for which I refreshed the page.

P.S. Besides that, this file takes 4 seconds to load, which is very long. Is this intended behavior?

**Comment by samuelli** [comment]
Hmm, we've made some changes so I'll re-deploy to prod. Let me know if you see the same error again.

I think some improvements have been made on performance, and we'll continue to do a little more. Unfortunately its kinda based on how much activity you have, so if you want the dashboard to be faster, do less Tim!

Closing this for now, since its not clearly actionable.
