### ISSUE TITLE
Need a way to toggle display of items with no action required

### ISSUE THREAD

**Issue by dstockwell** [PolymerLabs/project-health#265]

**Comment by samuelli** [comment]
Are you seeing lots of items that's making it noisy? I'm hesitant to add new features without a clear upside. There's some cases where we're not sure if you care about the pull request, for example, when there are new commits after you've already approved a PR, you may wish to take a look at these commits.

Blue/orange is meant to mark actionable/non-actionable otherwise.

**Comment by dstockwell** [comment]
It's not that there are too many items. Just that I was looking to treat the dashboard as a list of things I need to do. If it's empty, then I'm done. But if it lists a bunch of "no action required" I have to scan them. The colors do help a little.

I guess GitHub doesn't really have enough state to track that I've looked at new commits or comments after approving a PR, would it make sense to be able to ack those on the dashboard?

**Comment by samuelli** [comment]
There's 2 main features which are meant to help address the scanning part:
 - as mentioned, colors
 - outgoing is sorted by date created, but incoming is sorted by actionability (oranges at the top, blues at the bottom).

We could add acking, but have currently opted for minimal interactions.

How about re-opening this if it still is an issue in a couple of weeks?
