### ISSUE TITLE
Manually add repositories to crawl for incoming PRs

### ISSUE THREAD

**Issue by surma** [PolymerLabs/project-health#330]
## The Problem
I’d like to manually add repositories to crawl for incoming PRs. 

Use-case: I am the de-factor owner of GoogleChromeLabs/ui-element-samples, but since I am not assigned as reviewer to the PRs or the actual owner of that repo, the PRs don’t show up.

**Comment by samuelli** [comment]
We have 2 main ways of addressing this:
 - one is to utilise GitHub code owners file. You can find an explanation of recommended practices at go/devx. It allows you to have reviewers auto assigned.
 - we'll be able project level info (more than just issues). 

Closing this as a won't fix since we'll be addressing the underlying issue in different ways. Thanks for the feedback!

**Comment by surma** [comment]
TIL `CODEOWNERS`. Thanks!
