### ISSUE TITLE
Incoming dash request fails for user TimvdLippe

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerLabs/project-health#359]
## The Problem

The website does not load for my user (https://github-health.appspot.com/?login=timvdlippe)

![image](https://user-images.githubusercontent.com/5948271/37875370-5c5c095e-303e-11e8-99ba-0168c4dc9fb0.png)

It appears that https://github-health.appspot.com/api/dash/incoming is returning 500 errors:

```
<html><head>
<meta http-equiv="content-type" content="text/html;charset=utf-8">
<title>500 Server Error</title>
</head>
<body text=#000000 bgcolor=#ffffff>
<h1>Error: Server Error</h1>
<h2>The server encountered an error and could not complete your request.<p>Please try again in 30 seconds.</h2>
<h2></h2>
</body></html>
```

## Expected Behavior

The site loads for my user :wink:  

## Links to Relevant PR's / Issues

N/A

**Comment by gauntface** [comment]
It worked for me :(

**Comment by TimvdLippe** [comment]
Hm thats weird, because the above URL is still not showing me any pull
request.

**Comment by samuelli** [comment]
My guess is there's something in your private data that's causing a failure somewhere.

Here are all the relevant logs I could find:
![image](https://user-images.githubusercontent.com/787668/37985803-9d137c54-31ae-11e8-86d5-13f65f0e513d.png)
![image](https://user-images.githubusercontent.com/787668/37985816-a307e1f4-31ae-11e8-8d5c-c9e1e0522cc2.png).

Each has this error:
```
A problem was encountered with the process that handled this request, causing it to exit. This is likely to cause a new process to be used for the next request to your application. (Error code 204)
```

The latter ones are interesting because they're just static files. There's not much that happens for those, but that might be a red herring because of the initial failures.

**Comment by samuelli** [comment]
@TimvdLippe: I'm still unable to reproduce. Can you provide more info? Does this always happen? Does this happen on your homepage (ie. without the `login` param)?

**Comment by samuelli** [comment]
@TimvdLippe: if you see this error again, please file a new bug! Thanks.
