### ISSUE TITLE
Test recording is broken

### ISSUE THREAD

**Issue by samuelli** [PolymerLabs/project-health#72]
Broken because we now test against the build directory. The replays need to be stored in the src/ directory though.

**Comment by gauntface** [comment]
Options:

1. Write files to root (i.e. we'd have `replays/`, `src/`, `build/`)
1. Fix the write path to always write to `src/`

Would probably prefer the first option.

Also worth noting that replays at the moment need to be created by @samuelli because some of the tests expect those values. Not sure of the best approach to get around this beyond less strict tests (i.e. length great 0) or replacing specific values in the output (i.e. swap out <current username> with "TestUser").

**Comment by samuelli** [comment]
The `test:record` command should pretty much only be used with a `--match`. Each time a particular query is changed, we'll need to regenerate the test. As long as the GitHub queries are valid, then the test is testing that our code is correctly processing and producing the expected output.

We do have 2 test user accounts which some of the newer tests have been using. The test then always requests data for that user, so it shouldn't matter whose token you have to record the test. See server-test for this.

**Comment by samuelli** [comment]
1. is probably best. I can take a look at that.
